// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketApp.Models;

#nullable disable

namespace TicketApp.Migrations
{
    [DbContext(typeof(TicketsContext))]
    partial class TicketsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScheduleClass", b =>
                {
                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    b.HasKey("ScheduleId", "ClassId")
                        .HasName("schedule_class_PK");

                    b.HasIndex("ClassId");

                    b.ToTable("schedule_class", (string)null);
                });

            modelBuilder.Entity("TicketApp.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("name");

                    b.HasKey("ClassId");

                    b.ToTable("class", (string)null);
                });

            modelBuilder.Entity("TicketApp.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .HasColumnType("integer")
                        .HasColumnName("passenger_id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birthDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("surname");

                    b.HasKey("PassengerId");

                    b.ToTable("passengers", (string)null);
                });

            modelBuilder.Entity("TicketApp.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("reservation_id");

                    b.Property<int?>("NumTickets")
                        .HasColumnType("integer")
                        .HasColumnName("num_tickets");

                    b.Property<int?>("PassengerId")
                        .HasColumnType("integer")
                        .HasColumnName("passenger_id");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    b.HasKey("ReservationId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("TicketApp.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("integer")
                        .HasColumnName("route_id");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_id");

                    b.Property<int>("Distance")
                        .HasColumnType("integer")
                        .HasColumnName("distance");

                    b.Property<int?>("OriginId")
                        .HasColumnType("integer")
                        .HasColumnName("origin_id");

                    b.HasKey("RouteId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("TicketApp.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    b.Property<DateOnly>("DepartureTime")
                        .HasColumnType("date")
                        .HasColumnName("departure_time");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer")
                        .HasColumnName("route_id");

                    b.Property<int>("TrainId")
                        .HasColumnType("integer")
                        .HasColumnName("train_id");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ClassId");

                    b.HasIndex("RouteId");

                    b.HasIndex("TrainId");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("TicketApp.Models.Station", b =>
                {
                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("StationId");

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("TicketApp.Models.Train", b =>
                {
                    b.Property<int>("TrainId")
                        .HasColumnType("integer")
                        .HasColumnName("train_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("TrainId");

                    b.ToTable("train", (string)null);
                });

            modelBuilder.Entity("ScheduleClass", b =>
                {
                    b.HasOne("TicketApp.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("class_FK");

                    b.HasOne("TicketApp.Models.Schedule", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("schedule_FK");
                });

            modelBuilder.Entity("TicketApp.Models.Reservation", b =>
                {
                    b.HasOne("TicketApp.Models.Passenger", "Passenger")
                        .WithMany("Reservations")
                        .HasForeignKey("PassengerId")
                        .HasConstraintName("reservation_passengerFK");

                    b.HasOne("TicketApp.Models.Schedule", "Schedule")
                        .WithMany("Reservations")
                        .HasForeignKey("ScheduleId")
                        .HasConstraintName("reservation_scheduleFK");

                    b.Navigation("Passenger");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("TicketApp.Models.Route", b =>
                {
                    b.HasOne("TicketApp.Models.Station", "Destination")
                        .WithMany("RouteDestinations")
                        .HasForeignKey("DestinationId")
                        .HasConstraintName("routes_destionationFK");

                    b.HasOne("TicketApp.Models.Station", "Origin")
                        .WithMany("RouteOrigins")
                        .HasForeignKey("OriginId")
                        .HasConstraintName("routes_originFK");

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("TicketApp.Models.Schedule", b =>
                {
                    b.HasOne("TicketApp.Models.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("schedule_classFK");

                    b.HasOne("TicketApp.Models.Route", "Route")
                        .WithMany("Schedules")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("schedules_routeFK");

                    b.HasOne("TicketApp.Models.Train", "Train")
                        .WithMany("Schedules")
                        .HasForeignKey("TrainId")
                        .IsRequired()
                        .HasConstraintName("schedules_trainFK");

                    b.Navigation("Class");

                    b.Navigation("Route");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("TicketApp.Models.Class", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("TicketApp.Models.Passenger", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TicketApp.Models.Route", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("TicketApp.Models.Schedule", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TicketApp.Models.Station", b =>
                {
                    b.Navigation("RouteDestinations");

                    b.Navigation("RouteOrigins");
                });

            modelBuilder.Entity("TicketApp.Models.Train", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
